#!/bin/bash

# Recompile
mvn clean install

# Check if compiled ok
if [ $? -ne 0 ]; then
    echo "error: failed to compile" >&2
    exit 1
fi

# FOR CLIENT:
#
# FOR SERVER
# 00:16:30.959 ERROR [main] com.io7m.aeron_guide.take2.EchoServer: usage: directory local-address local-initial-data-port local-initial-control-port local-clients-base-port client-count

AERON_SERVER_PORT=33000
AERON_SERVER_IP=192.168.1.118

AERON_SERVER_DATA_DIR=/run/shm/my-aeron-server-take2

# Let's rock!
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
  mvn \
  "-Dexec.args=-classpath %classpath com.io7m.aeron_guide.take2.EchoServer ${AERON_SERVER_DATA_DIR} ${AERON_SERVER_IP} 44000 44001 55000 100" \
   -Dexec.executable=/usr/lib/jvm/java-8-openjdk-amd64/bin/java \
   org.codehaus.mojo:exec-maven-plugin:1.5.0:exec
