#!/bin/bash

# Recompile
mvn clean install

# Check if compiled ok
if [ $? -ne 0 ]; then
    echo "error: failed to compile" >&2
    exit 1
fi

# FOR CLIENT:
# 22:29:24.216 ERROR [main] com.io7m.aeron_guide.take1.EchoClient: usage: directory local-address local-port remote-address remote-port
#
# FOR SERVER
# 22:37:36.651 ERROR [main] com.io7m.aeron_guide.take1.EchoServer: usage: directory local-address local-port

AERON_SERVER_PORT=33000
AERON_SERVER_IP=127.0.0.1

AERON_SERVER_DATA_DIR=/run/shm/my-aeron-server-take1

# Let's rock!
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
  mvn \
  "-Dexec.args=-classpath %classpath com.io7m.aeron_guide.take1.EchoServer ${AERON_SERVER_DATA_DIR} ${AERON_SERVER_IP} ${AERON_SERVER_PORT}" \
   -Dexec.executable=/usr/lib/jvm/java-8-openjdk-amd64/bin/java \
   org.codehaus.mojo:exec-maven-plugin:1.5.0:exec
